vich_uploader:
    db_driver: orm

    mappings:
        file_attachments:
            uri_prefix: /files/upload
            upload_destination: '%kernel.project_dir%/public/files/upload'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
